//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftOpenTech.PuppetProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftOpenTech.PuppetProject.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Puppet Module is Empty.
        /// </summary>
        internal static string EmptyModule {
            get {
                return ResourceManager.GetString("EmptyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is mandatory..
        /// </summary>
        internal static string IsMandatoryTempl {
            get {
                return ResourceManager.GetString("IsMandatoryTempl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Module Name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Module Version.
        /// </summary>
        internal static string ModuleVersion {
            get {
                return ResourceManager.GetString("ModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Puppet Module Found.
        /// </summary>
        internal static string NoActivePuppetModule {
            get {
                return ResourceManager.GetString("NoActivePuppetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet Module Uploaded Successfully.
        /// </summary>
        internal static string PuppetModuleUploadedSuccessfully {
            get {
                return ResourceManager.GetString("PuppetModuleUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet Module Upload Staus.
        /// </summary>
        internal static string PuppetModuleUploadStatus {
            get {
                return ResourceManager.GetString("PuppetModuleUploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected project is not a Puppet Module.
        /// </summary>
        internal static string SelectedProjectIsNotAPuppetModule {
            get {
                return ResourceManager.GetString("SelectedProjectIsNotAPuppetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned &apos;{0}&apos; with the status code &apos;{1} ({2:d})&apos;..
        /// </summary>
        internal static string ServerReturnedTemplate {
            get {
                return ResourceManager.GetString("ServerReturnedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarball Creation Status.
        /// </summary>
        internal static string TarballCreationStatus {
            get {
                return ResourceManager.GetString("TarballCreationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarball was created and saved successfully.
        /// </summary>
        internal static string TarballSavedSuccessfully {
            get {
                return ResourceManager.GetString("TarballSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet Forge Window.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge User Password.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
